apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "releasemanager.fullname" . }}
  labels:
    app: {{ template "releasemanager.name" . }}
    chart: {{ template "releasemanager.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "releasemanager.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "releasemanager.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
          - watch
          - {{ required "A valid .Values.backend.type entry required!" .Values.backend.type }}
          - --path
          - {{ required "A valid .Values.backend.storagePath entry required!" .Values.backend.storagePath }}
          - --manager-release
          - {{ tpl (.Release.Name) .}}
{{- if .Values.config }}
          - --config
          - {{ .Values.config }}
{{- end }}
{{- if .Values.debug }}
          - --debug
{{- end }}
{{- if .Values.verbose }}
          - --verbose
{{- end }}
{{- if .Values.pollingInterval }}
          - --polling-interval
          - {{ .Values.pollingInterval }}
{{- end }}
{{- if .Values.tillerNamespace }}
          - --namespace
          - {{ .Values.tillerHost }}
{{- end }}
{{- if .Values.tillerNamespace }}
          - --tiller-host
          - {{ .Values.tillerHost }}
{{- end }}
{{- if and .Values.s3 (eq .Values.backend.type "s3") }}
          - --region
          - {{ required "A valid .Values.s3.region entry required!" .Values.s3.region }}
          - --bucket
          - {{ required "A valid .Values.s3.bucket entry required!" .Values.s3.bucket }}
{{- range $key, $value := .Values.s3 }}
{{- if and (ne $key "bucket") (ne $key "region") }}
          - --{{ $key }}
          - {{ $value }}
{{- end }}
{{- end }}
{{- else }}
{{- required "A valid .Values.s3 entry required!" .Values.s3 }}
{{- end }}
{{- if .Values.environment }}
          env:
  {{- range .Values.environment }}
          - name: {{ .name }}
            value: {{ .value }}
  {{- end }}
{{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
